### Getting notes OK

GET https://cuddly-meme-456pqv4vgrvc7prw-3001.app.github.dev/api/notes


### Deleting notes
DELETE https://cuddly-meme-456pqv4vgrvc7prw-3001.app.github.dev/api/notes/6

### POSTING notes

POST https://cuddly-meme-456pqv4vgrvc7prw-3001.app.github.dev/api/notes
Content-Type: application/json

{
    "content": "Saint André et sa croix",
    "important": "true"
}