GET https://cuddly-meme-456pqv4vgrvc7prw-3001.app.github.dev/api/notes

###
POST https://cuddly-meme-456pqv4vgrvc7prw-3001.app.github.dev/api/notes
Content-Type: application/json

{
   "content": "today is the 19/03/2026 in the fiest of Holy Joseph",
   "important": true
}