###Get every entries
GET https://shiny-space-winner-4j79pw6wv9727j79-3001.app.github.dev/api/persons


###Adding new people entry

POST https://shiny-space-winner-4j79pw6wv9727j79-3001.app.github.dev/api/persons
content-type: application/json

{
    "name": "Paul de THèbes",
    "number": "87864542"
}