###Get every entries
GET http://localhost:3001/api/persons

###Adding new people entry

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "LU",
    "number": "789456"
}

###Deleting an entry
DELETE http://localhost:3001/api/persons/6a045a9894be57c21e863f17

###Updating an entry
PUT http://localhost:3001/api/persons/6a045a9894be57c21e863f17
Content-Type: application/json

{
    "name": "Barnabé",
    "number": "0153818219"
}

